export const HOTEL_REQUEST = "HOTEL_REQUEST";
export const HOTEL_SUCCESS = "HOTEL_SUCCESS";

export const HOTEL_SEARCH_INFO_REQUEST = "HOTEL_SEARCH_INFO_REQUEST";
export const HOTEL_SEARCH_INFO_SUCCESS = "HOTEL_SEARCH_INFO_SUCCESS";

export const HOTEL_ROOM_REQUEST = "HOTEL_ROOM_REQUEST";
export const HOTEL_ROOM_SUCCESS = "HOTEL_ROOM_SUCCESS";

export const HOTEL_BLOCKROOM_REQUEST = "HOTEL_BLOCKROOM_REQUEST";
export const HOTEL_BLOCKROOM_SUCCESS = "HOTEL_BLOCKROOM_SUCCESS";

export const HOTEL_B0OKROOM_REQUEST = "HOTEL_B0OKROOM_REQUEST";
export const HOTEL_B0OKROOM_SUCCESS = "HOTEL_B0OKROOM_SUCCESS";

export const HOTEL_DETAILS_REQUEST = "HOTEL_DETAILS_REQUEST";
export const HOTEL_DETAILS_SUCCESS = "HOTEL_DETAILS_SUCCESS";

export const CLEAR_HOTEL_REDUCER = "CLEAR_HOTEL_REDUCER";
export const CLEAR_HOTEL_BLOCK_ROOM = "CLEAR_HOTEL_BLOCK_ROOM";
export const CLEAR_HOTEL_ROOM = "CLEAR_HOTEL_ROOM";
