export const RULE_REQUEST = "RULE_REQUEST";
export const RULE_SUCCESS = "RULE_SUCCESS";

export const QUOTE_REQUEST = "QUOTE_REQUEST";
export const QUOTE_SUCCESS = "QUOTE_SUCCESS";
export const CLEAR_FARE_DETAILS_REDUCER = "CLEAR_FARE_DETAILS_REDUCER";
export const CLEAR_ALL_FARE_DETAILS_REDUCER = "CLEAR_ALL_FARE_DETAILS_REDUCER";