export const FLIGHT_HOTAL_LIST_REQ="FLIGHT_HOTAL_LIST_REQ";
export const FLIGHT_HOTAL_SUCESS="FLIGHT_HOTAL_SUCESS"
export const FLIGHT_HOTEL_FAILED="FLIGHT_HOTEL_FAILED"
export const FLIGHT_HOTAL_CLEAR="FLIGHT_HOTAL_CLEAR"