export const NEW_FLIGHT_BOOK_REQUEST_ONEWAY = "NEW_FLIGHT_BOOK_REQUEST_ONEWAY"
export const NEW_FLIGHT_BOOK_SUCESS_ONEWAY = "NEW_FLIGHT_BOOK_SUCESS_ONEWAY"
export const NEW_FLIGHT_BOOK_REQUEST_RETURN = "NEW_FLIGHT_BOOK_REQUEST_REETURN"
export const NEW_FLIGHT_BOOK_FAIL_ONEWAY = "NEW_FLIGHT_BOOK_SUCESS_ONEWAY"
export const NEW_FLIGHT_BOOK_FAIL_RETURN = "NEW_FLIGHT_BOOK_REQUEST_REETURN"
export const NEW_FLIGHT_BOOK_SUCESS_RETURN = "NEW_FLIGHT_BOOK_SUCESS_RETRUN"
export const CLEAR_ALL_NEW_FILGHT_BOOK = "CLEAR_ALL_NEW_FILGHT_BOOK";