export const INVENTORY_LOGIN_SUCCESS="INVENTORY_LOGIN_SUCCESS";
export const  INVENTORY_LOGOUT_SUCCESS="INVENTORY_LOGOUT_SUCCESS";
export const INVENTORY_LOGIN_REQUEST="INVENTORY_LOGIN_REQUEST";

export const INVENTORY_LOGIN_FAILURE="INVENTORY_LOGIN_FAILURE";