export const FLIGHT_BOOK_REQUEST = "FLIGHT_BOOK_REQUEST";
export const FLIGHT_BOOK_SUCCESS = "FLIGHT_BOOK_SUCCESS";
export const FLIGHT_BOOK_REQUEST_GDS = "FLIGHT_BOOK_REQUEST_GDS";
export const FLIGHT_BOOK_SUCCESS_GDS = "FLIGHT_BOOK_SUCCESS_GDS";
export const FLIGHT_TICKET_REQUEST_GDS = "FLIGHT_TICKET_REQUEST_GDS";
export const FLIGHT_TICKET_SUCCESS_GDS = "FLIGHT_TICKET_SUCCESS_GDS";
export const FLIGHT_BOOK_CLEAR_ALL_REDUCER = "FLIGHT_BOOK_CLEAR_ALL_REDUCER";



export const FLIGHT_BOOK_REQUEST_RETURN = "FLIGHT_BOOK_REQUEST_RETURN";
export const FLIGHT_BOOK_SUCCESS_RETURN = "FLIGHT_BOOK_SUCCESS_RETURN";
export const FLIGHT_BOOK_REQUEST_GDS_RETURN = "FLIGHT_BOOK_REQUEST_GDS_RETURN";
export const FLIGHT_BOOK_SUCCESS_GDS_RETURN = " FLIGHT_BOOK_SUCCESS_GDS_RETURN";
export const FLIGHT_TICKET_REQUEST_GDS_RETURN = "FLIGHT_TICKET_REQUEST_GDS_RETURN";
export const FLIGHT_TICKET_SUCCESS_GDS_RETURN = "FLIGHT_TICKET_SUCCESS_GDS_RETURN";
export const FLIGHT_REDUCER_CLEAR = "FLIGHT_REDUCER_CLEAR";
