export const HOTEL_REQUESTGRN = "HOTEL_REQUESTGRN";
export const HOTEL_SUCCESSGRN = "HOTEL_SUCCESSGRN";

export const HOTEL_SINGLE_DETAIL_REQUEST = "HOTEL_SINGLE_DETAIL_REQUEST"
export const HOTEL_SINGLE_SUCCESS = "HOTEL_SINGLE_SUCCESS"

export const HOTEL_ROOMSELECT_REQUEST = "HOTEL_ROOMSELECT_REQUEST"
export const HOTEL_ROOMSELECT_SUCCESS = "HOTEL_ROOMSELECT_SUCCESS"

export const HOTEL_GALLERY_REQUEST = "HOTEL_GALLERY_REQUEST";
export const HOTEL_GALLERY_SUCCESS = "HOTEL_GALLERY_SUCCESS"

export const HOTEL_B0OKROOM_REQUESTGRN = "HOTEL_B0OKROOM_REQUESTGRN";
export const HOTEL_B0OKROOM_SUCCESSGRN = "HOTEL_B0OKROOM_SUCCESSGRN";

export const CLEAR_HOTEL_REDUCER_GRN = "CLEAR_HOTEL_REDUCER_GRN";
export const CLEAR_HOTEL_BLOCK_ROOM = "CLEAR_HOTEL_BLOCK_ROOM";
