export const PACKAGE_BOOK_REQUEST = "PACKAGE_BOOK_REQUEST";
export const PACKAGE_BOOK_SUCCESS = "PACKAGE_BOOK_SUCCESS";
export const PACKAGE_BOOK_FAILURE = "PACKAGE_BOOK_FAILURE";

export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL';