export const ONE_WAY_REQUEST = "ONE_WAY_REQUEST";
export const ONE_WAY_SUCCESS = "ONE_WAY_SUCCESS";

export const CLEAR_ONEWAY_REDUCER = "CLEAR_ONEWAY_REDUCER";
export const ONE_WAY_FAIL = "ONE_WAY_FAIL";


