export const PASSENGERS_REQUEST = "PASSENGERS_REQUEST";
export const PASSENGERS_SUCCESS = "PASSENGERS_SUCCESS";
export const PASSENGERS_REQUEST_RETURN = "PASSENGERS_REQUEST_RETURN";
export const PASSENGERS_SUCCESS_RETURN = "PASSENGERS_SUCCESS_RETURN";

export const CLEAR_PASSENGERS_REDUCER = "CLEAR_PASSENGERS_REDUCER";
