export const SEARCH_FLIGHT_LIST = "SEARCH_FLIGHT_LIST";
export const CLEAR_FLIGHT_LIST = "CLEAR_FLIGHT_LIST";
export const SEARCH_AIRPORT_LIST = "SEARCH_AIRPORT_LIST";
export const SEARCH_AIRPORT_LIST_REQ = "SEARCH_AIRPORT_LIST_REQ";
export const CLEAR_AIRPORT_LIST = "CLEAR_AIRPORT_LIST";
export const SEARCH_FLIGHT_LIST_REQ = "SEARCH_FLIGHT_LIST_REQ";

